# default config
baseURL = "https://www.leelasrecipes.com"
languageCode = "en-us"
title = "Leela's Recipes - Your home for delicious Indian Recipes"
theme = "parsa-hugo"
summaryLength = "10"
paginate = 12

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

# navigation
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Contact"
URL = "contact-us"
weight = 3

# defult parameter
[params]
logo = "images/logo.png"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "1"
# Meta data
description = "This is meta description"
# Preloader
preloader = true
# search
search = true
# about author
author = "Leela"
author_image = "images/banner-img.png"
bio = "I’m a Recipe Developer."
# Contact info
mobile = "content hidden"
email = "content hidden"
address = "India"
# Contact Form Action
contact_form_action = "#"
# Google Analytics
google_analitycs_id = "UA-48712319-10"
# copyright
copyright = "Copyright &copy; 2022 Leela's Recipes"

# Instagram feed
[params.instafeed]
enable = true
access_token = "###"

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/leelasrecipe"

[[params.social]]
icon = "ti-pinterest"
URL = "https://in.pinterest.com/leelasrecipe/"

[[params.social]]
icon = "ti-youtube"
URL = "https://www.youtube.com/channel/UCgMWHF6dNmRVZp6J4FZj51g"